version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.8.13
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./es/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:6.8.13
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
