version: '3'

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    depends_on:
      - prometheus
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./node_exporter/data:/host:ro,rslave

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    hostname: prometheus
    ports:
      - 9090:9090
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--web.external-url=prometheus'
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    depends_on:
      - prometheus
    ports:
      - 9091:9091

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    hostname: alertmanager
    depends_on:
      - prometheus
    ports:
      - 9093:9093
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
    volumes:
      - ./prom/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./prom/alertmanager:/alertmanager

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  chronograf:
    image: chronograf
    container_name: chronograf
    depends_on:
      - influxdb
    ports:
      - 8888:8888
    volumes:
      - ./chronograf/data:/var/lib/chronograf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    user: "472"
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/grafana.ini/:/etc/grafana/grafana.ini
      - ./grafana/plugins:/var/lib/grafana/plugins
