version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.1.1
    container_name: portainer-ce
    restart: always
    ports:
      - 19000:9000
    command: -H unix:///var/run/docker.sock
    environment:
      - MODE=standalone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
