version: '3'

services:
  elasticsearch:
    image: elasticsearch:6.8.11
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
